const CACHE_NAME = 'orbit-shell-v329';
const APP_SHELL = [
  './',
  './index.html',
  './styles.css?v=203',
  './boot.js?v=70',
  './workspace-core.js?v=2',
  './workspace-budget.js?v=2',
  './document-history.js?v=1',
  './workspace-tools.js?v=4',
  './document-assets.js?v=9',
  './document-edits.js?v=3',
  './long-documents.js?v=16',
  './analyze-sandbox.html',
  './chat-store.js?v=6',
  './analyze.js?v=14',
  './analyze-worker.js?v=2',
  './memories.js?v=10',
  './app.js?v=260',
  './file-preview.js?v=25',
  './vendor/sheetjs/xlsx.full.min.js',
  './thinking.js?v=11',
  './voice.js?v=1',
  './usage.js?v=4',
  './charts.js?v=3',
  './archives.js?v=2',
  './document-format.js?v=1',
  './widgets.js?v=62',
  './web-tools.js?v=15',
  './widgets-ui.js?v=43',
  './vendor/widgets/engine.js?v=28',
  './vendor/katex/katex.min.css',
  './vendor/katex/katex.min.js',
  './vendor/katex/KaTeX_AMS-Regular.woff2',
  './vendor/katex/KaTeX_Caligraphic-Bold.woff2',
  './vendor/katex/KaTeX_Caligraphic-Regular.woff2',
  './vendor/katex/KaTeX_Fraktur-Bold.woff2',
  './vendor/katex/KaTeX_Fraktur-Regular.woff2',
  './vendor/katex/KaTeX_Main-Bold.woff2',
  './vendor/katex/KaTeX_Main-BoldItalic.woff2',
  './vendor/katex/KaTeX_Main-Italic.woff2',
  './vendor/katex/KaTeX_Main-Regular.woff2',
  './vendor/katex/KaTeX_Math-BoldItalic.woff2',
  './vendor/katex/KaTeX_Math-Italic.woff2',
  './vendor/katex/KaTeX_SansSerif-Bold.woff2',
  './vendor/katex/KaTeX_SansSerif-Italic.woff2',
  './vendor/katex/KaTeX_SansSerif-Regular.woff2',
  './vendor/katex/KaTeX_Script-Regular.woff2',
  './vendor/katex/KaTeX_Size1-Regular.woff2',
  './vendor/katex/KaTeX_Size2-Regular.woff2',
  './vendor/katex/KaTeX_Size3-Regular.woff2',
  './vendor/katex/KaTeX_Size4-Regular.woff2',
  './vendor/katex/KaTeX_Typewriter-Regular.woff2',
  './vendor/readers/cmaps/78-EUC-H.bcmap',
  './vendor/readers/cmaps/78-EUC-V.bcmap',
  './vendor/readers/cmaps/78-H.bcmap',
  './vendor/readers/cmaps/78-RKSJ-H.bcmap',
  './vendor/readers/cmaps/78-RKSJ-V.bcmap',
  './vendor/readers/cmaps/78-V.bcmap',
  './vendor/readers/cmaps/78ms-RKSJ-H.bcmap',
  './vendor/readers/cmaps/78ms-RKSJ-V.bcmap',
  './vendor/readers/cmaps/83pv-RKSJ-H.bcmap',
  './vendor/readers/cmaps/90ms-RKSJ-H.bcmap',
  './vendor/readers/cmaps/90ms-RKSJ-V.bcmap',
  './vendor/readers/cmaps/90msp-RKSJ-H.bcmap',
  './vendor/readers/cmaps/90msp-RKSJ-V.bcmap',
  './vendor/readers/cmaps/90pv-RKSJ-H.bcmap',
  './vendor/readers/cmaps/90pv-RKSJ-V.bcmap',
  './vendor/readers/cmaps/Add-H.bcmap',
  './vendor/readers/cmaps/Add-RKSJ-H.bcmap',
  './vendor/readers/cmaps/Add-RKSJ-V.bcmap',
  './vendor/readers/cmaps/Add-V.bcmap',
  './vendor/readers/cmaps/Adobe-CNS1-0.bcmap',
  './vendor/readers/cmaps/Adobe-CNS1-1.bcmap',
  './vendor/readers/cmaps/Adobe-CNS1-2.bcmap',
  './vendor/readers/cmaps/Adobe-CNS1-3.bcmap',
  './vendor/readers/cmaps/Adobe-CNS1-4.bcmap',
  './vendor/readers/cmaps/Adobe-CNS1-5.bcmap',
  './vendor/readers/cmaps/Adobe-CNS1-6.bcmap',
  './vendor/readers/cmaps/Adobe-CNS1-UCS2.bcmap',
  './vendor/readers/cmaps/Adobe-GB1-0.bcmap',
  './vendor/readers/cmaps/Adobe-GB1-1.bcmap',
  './vendor/readers/cmaps/Adobe-GB1-2.bcmap',
  './vendor/readers/cmaps/Adobe-GB1-3.bcmap',
  './vendor/readers/cmaps/Adobe-GB1-4.bcmap',
  './vendor/readers/cmaps/Adobe-GB1-5.bcmap',
  './vendor/readers/cmaps/Adobe-GB1-UCS2.bcmap',
  './vendor/readers/cmaps/Adobe-Japan1-0.bcmap',
  './vendor/readers/cmaps/Adobe-Japan1-1.bcmap',
  './vendor/readers/cmaps/Adobe-Japan1-2.bcmap',
  './vendor/readers/cmaps/Adobe-Japan1-3.bcmap',
  './vendor/readers/cmaps/Adobe-Japan1-4.bcmap',
  './vendor/readers/cmaps/Adobe-Japan1-5.bcmap',
  './vendor/readers/cmaps/Adobe-Japan1-6.bcmap',
  './vendor/readers/cmaps/Adobe-Japan1-UCS2.bcmap',
  './vendor/readers/cmaps/Adobe-Korea1-0.bcmap',
  './vendor/readers/cmaps/Adobe-Korea1-1.bcmap',
  './vendor/readers/cmaps/Adobe-Korea1-2.bcmap',
  './vendor/readers/cmaps/Adobe-Korea1-UCS2.bcmap',
  './vendor/readers/cmaps/B5-H.bcmap',
  './vendor/readers/cmaps/B5-V.bcmap',
  './vendor/readers/cmaps/B5pc-H.bcmap',
  './vendor/readers/cmaps/B5pc-V.bcmap',
  './vendor/readers/cmaps/CNS-EUC-H.bcmap',
  './vendor/readers/cmaps/CNS-EUC-V.bcmap',
  './vendor/readers/cmaps/CNS1-H.bcmap',
  './vendor/readers/cmaps/CNS1-V.bcmap',
  './vendor/readers/cmaps/CNS2-H.bcmap',
  './vendor/readers/cmaps/CNS2-V.bcmap',
  './vendor/readers/cmaps/ETHK-B5-H.bcmap',
  './vendor/readers/cmaps/ETHK-B5-V.bcmap',
  './vendor/readers/cmaps/ETen-B5-H.bcmap',
  './vendor/readers/cmaps/ETen-B5-V.bcmap',
  './vendor/readers/cmaps/ETenms-B5-H.bcmap',
  './vendor/readers/cmaps/ETenms-B5-V.bcmap',
  './vendor/readers/cmaps/EUC-H.bcmap',
  './vendor/readers/cmaps/EUC-V.bcmap',
  './vendor/readers/cmaps/Ext-H.bcmap',
  './vendor/readers/cmaps/Ext-RKSJ-H.bcmap',
  './vendor/readers/cmaps/Ext-RKSJ-V.bcmap',
  './vendor/readers/cmaps/Ext-V.bcmap',
  './vendor/readers/cmaps/GB-EUC-H.bcmap',
  './vendor/readers/cmaps/GB-EUC-V.bcmap',
  './vendor/readers/cmaps/GB-H.bcmap',
  './vendor/readers/cmaps/GB-V.bcmap',
  './vendor/readers/cmaps/GBK-EUC-H.bcmap',
  './vendor/readers/cmaps/GBK-EUC-V.bcmap',
  './vendor/readers/cmaps/GBK2K-H.bcmap',
  './vendor/readers/cmaps/GBK2K-V.bcmap',
  './vendor/readers/cmaps/GBKp-EUC-H.bcmap',
  './vendor/readers/cmaps/GBKp-EUC-V.bcmap',
  './vendor/readers/cmaps/GBT-EUC-H.bcmap',
  './vendor/readers/cmaps/GBT-EUC-V.bcmap',
  './vendor/readers/cmaps/GBT-H.bcmap',
  './vendor/readers/cmaps/GBT-V.bcmap',
  './vendor/readers/cmaps/GBTpc-EUC-H.bcmap',
  './vendor/readers/cmaps/GBTpc-EUC-V.bcmap',
  './vendor/readers/cmaps/GBpc-EUC-H.bcmap',
  './vendor/readers/cmaps/GBpc-EUC-V.bcmap',
  './vendor/readers/cmaps/H.bcmap',
  './vendor/readers/cmaps/HKdla-B5-H.bcmap',
  './vendor/readers/cmaps/HKdla-B5-V.bcmap',
  './vendor/readers/cmaps/HKdlb-B5-H.bcmap',
  './vendor/readers/cmaps/HKdlb-B5-V.bcmap',
  './vendor/readers/cmaps/HKgccs-B5-H.bcmap',
  './vendor/readers/cmaps/HKgccs-B5-V.bcmap',
  './vendor/readers/cmaps/HKm314-B5-H.bcmap',
  './vendor/readers/cmaps/HKm314-B5-V.bcmap',
  './vendor/readers/cmaps/HKm471-B5-H.bcmap',
  './vendor/readers/cmaps/HKm471-B5-V.bcmap',
  './vendor/readers/cmaps/HKscs-B5-H.bcmap',
  './vendor/readers/cmaps/HKscs-B5-V.bcmap',
  './vendor/readers/cmaps/Hankaku.bcmap',
  './vendor/readers/cmaps/Hiragana.bcmap',
  './vendor/readers/cmaps/KSC-EUC-H.bcmap',
  './vendor/readers/cmaps/KSC-EUC-V.bcmap',
  './vendor/readers/cmaps/KSC-H.bcmap',
  './vendor/readers/cmaps/KSC-Johab-H.bcmap',
  './vendor/readers/cmaps/KSC-Johab-V.bcmap',
  './vendor/readers/cmaps/KSC-V.bcmap',
  './vendor/readers/cmaps/KSCms-UHC-H.bcmap',
  './vendor/readers/cmaps/KSCms-UHC-HW-H.bcmap',
  './vendor/readers/cmaps/KSCms-UHC-HW-V.bcmap',
  './vendor/readers/cmaps/KSCms-UHC-V.bcmap',
  './vendor/readers/cmaps/KSCpc-EUC-H.bcmap',
  './vendor/readers/cmaps/KSCpc-EUC-V.bcmap',
  './vendor/readers/cmaps/Katakana.bcmap',
  './vendor/readers/cmaps/NWP-H.bcmap',
  './vendor/readers/cmaps/NWP-V.bcmap',
  './vendor/readers/cmaps/RKSJ-H.bcmap',
  './vendor/readers/cmaps/RKSJ-V.bcmap',
  './vendor/readers/cmaps/Roman.bcmap',
  './vendor/readers/cmaps/UniCNS-UCS2-H.bcmap',
  './vendor/readers/cmaps/UniCNS-UCS2-V.bcmap',
  './vendor/readers/cmaps/UniCNS-UTF16-H.bcmap',
  './vendor/readers/cmaps/UniCNS-UTF16-V.bcmap',
  './vendor/readers/cmaps/UniCNS-UTF32-H.bcmap',
  './vendor/readers/cmaps/UniCNS-UTF32-V.bcmap',
  './vendor/readers/cmaps/UniCNS-UTF8-H.bcmap',
  './vendor/readers/cmaps/UniCNS-UTF8-V.bcmap',
  './vendor/readers/cmaps/UniGB-UCS2-H.bcmap',
  './vendor/readers/cmaps/UniGB-UCS2-V.bcmap',
  './vendor/readers/cmaps/UniGB-UTF16-H.bcmap',
  './vendor/readers/cmaps/UniGB-UTF16-V.bcmap',
  './vendor/readers/cmaps/UniGB-UTF32-H.bcmap',
  './vendor/readers/cmaps/UniGB-UTF32-V.bcmap',
  './vendor/readers/cmaps/UniGB-UTF8-H.bcmap',
  './vendor/readers/cmaps/UniGB-UTF8-V.bcmap',
  './vendor/readers/cmaps/UniJIS-UCS2-H.bcmap',
  './vendor/readers/cmaps/UniJIS-UCS2-HW-H.bcmap',
  './vendor/readers/cmaps/UniJIS-UCS2-HW-V.bcmap',
  './vendor/readers/cmaps/UniJIS-UCS2-V.bcmap',
  './vendor/readers/cmaps/UniJIS-UTF16-H.bcmap',
  './vendor/readers/cmaps/UniJIS-UTF16-V.bcmap',
  './vendor/readers/cmaps/UniJIS-UTF32-H.bcmap',
  './vendor/readers/cmaps/UniJIS-UTF32-V.bcmap',
  './vendor/readers/cmaps/UniJIS-UTF8-H.bcmap',
  './vendor/readers/cmaps/UniJIS-UTF8-V.bcmap',
  './vendor/readers/cmaps/UniJIS2004-UTF16-H.bcmap',
  './vendor/readers/cmaps/UniJIS2004-UTF16-V.bcmap',
  './vendor/readers/cmaps/UniJIS2004-UTF32-H.bcmap',
  './vendor/readers/cmaps/UniJIS2004-UTF32-V.bcmap',
  './vendor/readers/cmaps/UniJIS2004-UTF8-H.bcmap',
  './vendor/readers/cmaps/UniJIS2004-UTF8-V.bcmap',
  './vendor/readers/cmaps/UniJISPro-UCS2-HW-V.bcmap',
  './vendor/readers/cmaps/UniJISPro-UCS2-V.bcmap',
  './vendor/readers/cmaps/UniJISPro-UTF8-V.bcmap',
  './vendor/readers/cmaps/UniJISX0213-UTF32-H.bcmap',
  './vendor/readers/cmaps/UniJISX0213-UTF32-V.bcmap',
  './vendor/readers/cmaps/UniJISX02132004-UTF32-H.bcmap',
  './vendor/readers/cmaps/UniJISX02132004-UTF32-V.bcmap',
  './vendor/readers/cmaps/UniKS-UCS2-H.bcmap',
  './vendor/readers/cmaps/UniKS-UCS2-V.bcmap',
  './vendor/readers/cmaps/UniKS-UTF16-H.bcmap',
  './vendor/readers/cmaps/UniKS-UTF16-V.bcmap',
  './vendor/readers/cmaps/UniKS-UTF32-H.bcmap',
  './vendor/readers/cmaps/UniKS-UTF32-V.bcmap',
  './vendor/readers/cmaps/UniKS-UTF8-H.bcmap',
  './vendor/readers/cmaps/UniKS-UTF8-V.bcmap',
  './vendor/readers/cmaps/V.bcmap',
  './vendor/readers/cmaps/WP-Symbol.bcmap',
  './vendor/readers/jszip.min.js',
  './vendor/readers/mammoth.browser.min.js',
  './vendor/readers/pdf.min.mjs',
  './vendor/readers/pdf.worker.min.mjs',
  './vendor/readers/standard_fonts/FoxitDingbats.pfb',
  './vendor/readers/standard_fonts/FoxitFixed.pfb',
  './vendor/readers/standard_fonts/FoxitFixedBold.pfb',
  './vendor/readers/standard_fonts/FoxitFixedBoldItalic.pfb',
  './vendor/readers/standard_fonts/FoxitFixedItalic.pfb',
  './vendor/readers/standard_fonts/FoxitSerif.pfb',
  './vendor/readers/standard_fonts/FoxitSerifBold.pfb',
  './vendor/readers/standard_fonts/FoxitSerifBoldItalic.pfb',
  './vendor/readers/standard_fonts/FoxitSerifItalic.pfb',
  './vendor/readers/standard_fonts/FoxitSymbol.pfb',
  './vendor/readers/standard_fonts/LiberationSans-Bold.ttf',
  './vendor/readers/standard_fonts/LiberationSans-BoldItalic.ttf',
  './vendor/readers/standard_fonts/LiberationSans-Italic.ttf',
  './vendor/readers/standard_fonts/LiberationSans-Regular.ttf',
  './manifest.webmanifest',
  './icon.svg',
];

self.addEventListener('install', (event) => {
  event.waitUntil(caches.open(CACHE_NAME).then(async cache => {
    await cache.addAll(APP_SHELL);
    // Scientific runtime is bundled locally; cache it for offline reopen too.
    const response=await fetch('./vendor/analyze/manifest.json');
    if(!response.ok)throw new Error('Analyze runtime missing');
    const manifest=await response.json();
    await cache.addAll(['./vendor/analyze/manifest.json',...manifest.files.map(f=>`./vendor/analyze/${f.name}`)]);
  }));
  self.skipWaiting();
});

self.addEventListener('activate', (event) => {
  event.waitUntil(caches.keys().then((keys) => Promise.all(keys.filter((key) => key !== CACHE_NAME).map((key) => caches.delete(key)))));
  self.clients.claim();
});

self.addEventListener('fetch', (event) => {
  if (event.request.method !== 'GET') return;
  const url = new URL(event.request.url);
  if (url.origin !== self.location.origin || url.pathname.startsWith('/api/')) return;
  event.respondWith(fetch(event.request).then((response) => {
    if (response.ok) {
      const copy = response.clone();
      event.waitUntil(caches.open(CACHE_NAME).then((cache) => cache.put(event.request, copy)).catch(() => {}));
    }
    return response;
  }).catch(() => caches.match(event.request, { ignoreSearch: true }).then((cached) => {
    if (cached) return cached;
    if (event.request.mode === 'navigate') return caches.match('./index.html');
    return Response.error();
  })));
});
